"""co-product output ratios and asymmetric merge consumption

Revision ID: 060d790180d5
Revises: 5a3b1e305c7b
Create Date: 2026-08-19 16:13:25.466835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '060d790180d5'
down_revision: Union[str, None] = '5a3b1e305c7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_step_output',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('output_item_id', sa.String(length=64), nullable=False),
    sa.Column('output_ratio', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['step_id'], ['process_step.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('step_id', 'output_item_id')
    )
    op.create_index(op.f('ix_process_step_output_step_id'), 'process_step_output', ['step_id'], unique=False)
    op.drop_column('process_step', 'output_item_id')
    op.add_column('process_step_transition', sa.Column('output_item_id', sa.String(length=64), nullable=True))
    op.add_column('process_step_transition', sa.Column('consumption_ratio', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('process_step_transition', 'consumption_ratio')
    op.drop_column('process_step_transition', 'output_item_id')
    op.add_column('process_step', sa.Column('output_item_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_process_step_output_step_id'), table_name='process_step_output')
    op.drop_table('process_step_output')
    # ### end Alembic commands ###
