"""batch fields and material inbound plan

Revision ID: 2fa6467f4bdd
Revises: 336ad007b562
Create Date: 2026-08-13 11:06:46.597858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2fa6467f4bdd'
down_revision: Union[str, None] = '336ad007b562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_inbound_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('location_id', sa.String(length=64), nullable=False),
    sa.Column('inbound_qty', sa.Float(), nullable=False),
    sa.Column('inbound_unit', sa.String(length=16), nullable=True),
    sa.Column('interval_value', sa.Float(), nullable=False),
    sa.Column('interval_unit', sa.String(length=16), nullable=False),
    sa.Column('schema_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_inbound_plan_item_id'), 'material_inbound_plan', ['item_id'], unique=False)
    op.create_index(op.f('ix_material_inbound_plan_location_id'), 'material_inbound_plan', ['location_id'], unique=False)
    op.create_index(op.f('ix_material_inbound_plan_plan_id'), 'material_inbound_plan', ['plan_id'], unique=True)
    op.add_column('process_step', sa.Column('batch_size', sa.Float(), nullable=True))
    op.add_column('process_step', sa.Column('batch_unit', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('process_step', 'batch_unit')
    op.drop_column('process_step', 'batch_size')
    op.drop_index(op.f('ix_material_inbound_plan_plan_id'), table_name='material_inbound_plan')
    op.drop_index(op.f('ix_material_inbound_plan_location_id'), table_name='material_inbound_plan')
    op.drop_index(op.f('ix_material_inbound_plan_item_id'), table_name='material_inbound_plan')
    op.drop_table('material_inbound_plan')
    # ### end Alembic commands ###
