"""master data and process routing tables

Revision ID: 336ad007b562
Revises: b638c3a1efa7
Create Date: 2026-08-13 10:36:36.532292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '336ad007b562'
down_revision: Union[str, None] = 'b638c3a1efa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.String(length=64), nullable=False),
    sa.Column('group_name', sa.String(length=256), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('default_capacity_source', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_group_group_id'), 'equipment_group', ['group_id'], unique=True)
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.String(length=64), nullable=False),
    sa.Column('location_type', sa.String(length=32), nullable=False),
    sa.Column('location_name', sa.String(length=256), nullable=True),
    sa.Column('storage_capacity', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_location_id'), 'location', ['location_id'], unique=True)
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.String(length=64), nullable=False),
    sa.Column('group_id', sa.String(length=64), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['equipment_group.group_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_equipment_id'), 'equipment', ['equipment_id'], unique=True)
    op.create_index(op.f('ix_equipment_group_id'), 'equipment', ['group_id'], unique=False)
    op.create_table('process_routing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('graph_completeness_status', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('updated_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'version')
    )
    op.create_index(op.f('ix_process_routing_product_id'), 'process_routing', ['product_id'], unique=False)
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=True),
    sa.Column('process_id', sa.String(length=64), nullable=True),
    sa.Column('process_group_id', sa.String(length=64), nullable=True),
    sa.Column('recipe_scope', sa.String(length=32), nullable=False),
    sa.Column('setup_time', sa.Float(), nullable=True),
    sa.Column('speed', sa.JSON(), nullable=True),
    sa.Column('length_factor', sa.JSON(), nullable=True),
    sa.Column('cable_recipe', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_recipe_id'), 'recipe', ['recipe_id'], unique=True)
    op.create_table('transport_route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.String(length=64), nullable=False),
    sa.Column('from_location_id', sa.String(length=64), nullable=False),
    sa.Column('to_location_id', sa.String(length=64), nullable=False),
    sa.Column('transport_mode', sa.String(length=32), nullable=True),
    sa.Column('transport_distance', sa.Float(), nullable=True),
    sa.Column('transport_speed', sa.Float(), nullable=True),
    sa.Column('transport_time', sa.Float(), nullable=True),
    sa.Column('transport_capacity_per_trip', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_location_id'], ['location.location_id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['location.location_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transport_route_from_location_id'), 'transport_route', ['from_location_id'], unique=False)
    op.create_index(op.f('ix_transport_route_route_id'), 'transport_route', ['route_id'], unique=True)
    op.create_index(op.f('ix_transport_route_to_location_id'), 'transport_route', ['to_location_id'], unique=False)
    op.create_table('process_step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routing_id', sa.Integer(), nullable=False),
    sa.Column('step_no', sa.String(length=32), nullable=False),
    sa.Column('process_id', sa.String(length=64), nullable=True),
    sa.Column('process_group_id', sa.String(length=64), nullable=True),
    sa.Column('process_name', sa.String(length=256), nullable=True),
    sa.Column('input_item_id', sa.String(length=64), nullable=True),
    sa.Column('output_item_id', sa.String(length=64), nullable=True),
    sa.Column('input_qty_per', sa.Float(), nullable=True),
    sa.Column('equipment_group', sa.String(length=64), nullable=True),
    sa.Column('std_speed', sa.Float(), nullable=True),
    sa.Column('std_time_per', sa.Float(), nullable=True),
    sa.Column('setup_time', sa.Float(), nullable=True),
    sa.Column('flow_type', sa.String(length=32), nullable=False),
    sa.Column('parallel_group_id', sa.String(length=64), nullable=True),
    sa.Column('join_condition', sa.String(length=256), nullable=True),
    sa.Column('production_type', sa.String(length=32), nullable=False),
    sa.Column('input_location_id', sa.String(length=64), nullable=True),
    sa.Column('output_location_id', sa.String(length=64), nullable=True),
    sa.Column('inbound_route_id', sa.String(length=64), nullable=True),
    sa.Column('process_specific', sa.JSON(), nullable=True),
    sa.Column('schema_status', sa.String(length=32), nullable=False),
    sa.Column('reference_status', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['routing_id'], ['process_routing.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('routing_id', 'step_no')
    )
    op.create_index(op.f('ix_process_step_routing_id'), 'process_step', ['routing_id'], unique=False)
    op.create_table('process_step_transition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_step_id', sa.Integer(), nullable=False),
    sa.Column('to_step_no', sa.String(length=32), nullable=False),
    sa.Column('condition', sa.String(length=256), nullable=False),
    sa.Column('interpreted_condition', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['from_step_id'], ['process_step.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_step_transition_from_step_id'), 'process_step_transition', ['from_step_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_process_step_transition_from_step_id'), table_name='process_step_transition')
    op.drop_table('process_step_transition')
    op.drop_index(op.f('ix_process_step_routing_id'), table_name='process_step')
    op.drop_table('process_step')
    op.drop_index(op.f('ix_transport_route_to_location_id'), table_name='transport_route')
    op.drop_index(op.f('ix_transport_route_route_id'), table_name='transport_route')
    op.drop_index(op.f('ix_transport_route_from_location_id'), table_name='transport_route')
    op.drop_table('transport_route')
    op.drop_index(op.f('ix_recipe_recipe_id'), table_name='recipe')
    op.drop_table('recipe')
    op.drop_index(op.f('ix_process_routing_product_id'), table_name='process_routing')
    op.drop_table('process_routing')
    op.drop_index(op.f('ix_equipment_group_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_equipment_id'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_location_location_id'), table_name='location')
    op.drop_table('location')
    op.drop_index(op.f('ix_equipment_group_group_id'), table_name='equipment_group')
    op.drop_table('equipment_group')
    # ### end Alembic commands ###
