"""simulation run tables

Revision ID: 37dff02c8593
Revises: 861be0e05be2
Create Date: 2026-08-18 13:55:05.182189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '37dff02c8593'
down_revision: Union[str, None] = '861be0e05be2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compile_run_id', sa.Integer(), nullable=False),
    sa.Column('runtime_profile_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('material_inbound_overrides', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['compile_run_id'], ['compile_run.id'], ),
    sa.ForeignKeyConstraint(['runtime_profile_id'], ['runtime_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_run_compile_run_id'), 'simulation_run', ['compile_run_id'], unique=False)
    op.create_table('simulation_event_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_run_id', sa.Integer(), nullable=False),
    sa.Column('sim_time', sa.Float(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('step_no', sa.String(length=32), nullable=True),
    sa.Column('resource_key', sa.String(length=64), nullable=True),
    sa.Column('item_id', sa.String(length=64), nullable=True),
    sa.Column('qty', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_event_log_simulation_run_id'), 'simulation_event_log', ['simulation_run_id'], unique=False)
    op.create_table('simulation_result_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_run_id', sa.Integer(), nullable=False),
    sa.Column('throughput_total', sa.Float(), nullable=False),
    sa.Column('throughput_per_day', sa.Float(), nullable=False),
    sa.Column('avg_wip', sa.Float(), nullable=True),
    sa.Column('avg_lead_time', sa.Float(), nullable=True),
    sa.Column('resource_utilization', sa.JSON(), nullable=False),
    sa.Column('bottleneck_step_no', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_result_summary_simulation_run_id'), 'simulation_result_summary', ['simulation_run_id'], unique=True)
    op.create_table('simulation_wip_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_run_id', sa.Integer(), nullable=False),
    sa.Column('sim_time', sa.Float(), nullable=False),
    sa.Column('total_wip', sa.Float(), nullable=False),
    sa.Column('by_step', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_wip_snapshot_simulation_run_id'), 'simulation_wip_snapshot', ['simulation_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulation_wip_snapshot_simulation_run_id'), table_name='simulation_wip_snapshot')
    op.drop_table('simulation_wip_snapshot')
    op.drop_index(op.f('ix_simulation_result_summary_simulation_run_id'), table_name='simulation_result_summary')
    op.drop_table('simulation_result_summary')
    op.drop_index(op.f('ix_simulation_event_log_simulation_run_id'), table_name='simulation_event_log')
    op.drop_table('simulation_event_log')
    op.drop_index(op.f('ix_simulation_run_compile_run_id'), table_name='simulation_run')
    op.drop_table('simulation_run')
    # ### end Alembic commands ###
