"""routing product link for shared multi-product networks

Revision ID: 3d4d0c083e33
Revises: 060d790180d5
Create Date: 2026-08-19 16:35:37.983032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3d4d0c083e33'
down_revision: Union[str, None] = '060d790180d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routing_product_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routing_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('entry_step_nos', sa.JSON(), nullable=True),
    sa.Column('terminal_step_nos', sa.JSON(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.ForeignKeyConstraint(['routing_id'], ['process_routing.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('routing_id', 'product_id')
    )
    op.create_index(op.f('ix_routing_product_link_product_id'), 'routing_product_link', ['product_id'], unique=False)
    op.create_index(op.f('ix_routing_product_link_routing_id'), 'routing_product_link', ['routing_id'], unique=False)
    op.add_column('compile_run', sa.Column('bound_product_ids', sa.JSON(), nullable=False))
    op.drop_index(op.f('ix_compile_run_product_id'), table_name='compile_run')
    op.drop_column('compile_run', 'product_id')
    op.add_column('simulation_result_summary', sa.Column('exit_qty_by_step', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulation_result_summary', 'exit_qty_by_step')
    op.add_column('compile_run', sa.Column('product_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_compile_run_product_id'), 'compile_run', ['product_id'], unique=False)
    op.drop_column('compile_run', 'bound_product_ids')
    op.drop_index(op.f('ix_routing_product_link_routing_id'), table_name='routing_product_link')
    op.drop_index(op.f('ix_routing_product_link_product_id'), table_name='routing_product_link')
    op.drop_table('routing_product_link')
    # ### end Alembic commands ###
