"""ingestion tables

Revision ID: 5a3b1e305c7b
Revises: 37dff02c8593
Create Date: 2026-08-18 14:36:30.934265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5a3b1e305c7b'
down_revision: Union[str, None] = '37dff02c8593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('original_filename', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requested_by', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upload_field_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_header_text_normalized', sa.String(length=256), nullable=False),
    sa.Column('common_field_id', sa.Integer(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['common_field_id'], ['meta_common_field.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_field_alias_raw_header_text_normalized'), 'upload_field_alias', ['raw_header_text_normalized'], unique=True)
    op.create_table('upload_field_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_job_id', sa.Integer(), nullable=False),
    sa.Column('source_label', sa.String(length=128), nullable=True),
    sa.Column('raw_header_text', sa.String(length=256), nullable=False),
    sa.Column('mapped_common_field_id', sa.Integer(), nullable=True),
    sa.Column('mapped_canonical_key', sa.String(length=128), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('decided_by', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['mapped_common_field_id'], ['meta_common_field.id'], ),
    sa.ForeignKeyConstraint(['upload_job_id'], ['upload_job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_field_mapping_upload_job_id'), 'upload_field_mapping', ['upload_job_id'], unique=False)
    op.create_table('upload_job_draft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_job_id', sa.Integer(), nullable=False),
    sa.Column('entity_key', sa.String(length=64), nullable=False),
    sa.Column('source_label', sa.String(length=128), nullable=True),
    sa.Column('records', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['upload_job_id'], ['upload_job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_job_draft_upload_job_id'), 'upload_job_draft', ['upload_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upload_job_draft_upload_job_id'), table_name='upload_job_draft')
    op.drop_table('upload_job_draft')
    op.drop_index(op.f('ix_upload_field_mapping_upload_job_id'), table_name='upload_field_mapping')
    op.drop_table('upload_field_mapping')
    op.drop_index(op.f('ix_upload_field_alias_raw_header_text_normalized'), table_name='upload_field_alias')
    op.drop_table('upload_field_alias')
    op.drop_table('upload_job')
    # ### end Alembic commands ###
