"""runtime profile and compile run tables

Revision ID: 861be0e05be2
Revises: 2fa6467f4bdd
Create Date: 2026-08-18 13:41:55.278166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '861be0e05be2'
down_revision: Union[str, None] = '2fa6467f4bdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runtime_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_name', sa.String(length=128), nullable=False),
    sa.Column('time_control', sa.JSON(), nullable=False),
    sa.Column('execution_mode', sa.JSON(), nullable=False),
    sa.Column('scenario_toggles', sa.JSON(), nullable=False),
    sa.Column('policy_refs', sa.JSON(), nullable=False),
    sa.Column('stochastic_defaults', sa.JSON(), nullable=False),
    sa.Column('output_control', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runtime_profile_profile_name'), 'runtime_profile', ['profile_name'], unique=True)
    op.create_table('compile_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routing_id', sa.Integer(), nullable=False),
    sa.Column('routing_version', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('runtime_profile_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('compiled_graph_object', sa.JSON(), nullable=True),
    sa.Column('validation_report', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['routing_id'], ['process_routing.id'], ),
    sa.ForeignKeyConstraint(['runtime_profile_id'], ['runtime_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compile_run_product_id'), 'compile_run', ['product_id'], unique=False)
    op.create_index(op.f('ix_compile_run_routing_id'), 'compile_run', ['routing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compile_run_routing_id'), table_name='compile_run')
    op.drop_index(op.f('ix_compile_run_product_id'), table_name='compile_run')
    op.drop_table('compile_run')
    op.drop_index(op.f('ix_runtime_profile_profile_name'), table_name='runtime_profile')
    op.drop_table('runtime_profile')
    # ### end Alembic commands ###
