"""meta schema and product tables

Revision ID: b638c3a1efa7
Revises: 
Create Date: 2026-08-13 10:19:17.277227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b638c3a1efa7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta_common_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_field_code', sa.String(length=64), nullable=False),
    sa.Column('canonical_key', sa.String(length=128), nullable=False),
    sa.Column('description_ko', sa.String(length=256), nullable=True),
    sa.Column('canonical_type', sa.String(length=32), nullable=False),
    sa.Column('value_role', sa.String(length=32), nullable=False),
    sa.Column('schema_status', sa.String(length=32), nullable=False),
    sa.Column('path_sensitive', sa.Boolean(), nullable=False),
    sa.Column('enum_domain', sa.JSON(), nullable=True),
    sa.Column('unit_family', sa.String(length=64), nullable=True),
    sa.Column('derived_from', sa.JSON(), nullable=True),
    sa.Column('formula_id', sa.String(length=64), nullable=True),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta_common_field_common_field_code'), 'meta_common_field', ['common_field_code'], unique=True)
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('product_name', sa.String(length=256), nullable=False),
    sa.Column('product_type', sa.String(length=32), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('cable_design', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_product_id'), 'product', ['product_id'], unique=True)
    op.create_table('meta_field_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_mapping_code', sa.String(length=64), nullable=False),
    sa.Column('common_field_id', sa.Integer(), nullable=True),
    sa.Column('canonical_key', sa.String(length=128), nullable=False),
    sa.Column('path_patterns', sa.JSON(), nullable=False),
    sa.Column('entity_scope', sa.String(length=64), nullable=False),
    sa.Column('canonical_type', sa.String(length=32), nullable=False),
    sa.Column('editable', sa.Boolean(), nullable=False),
    sa.Column('value_role', sa.String(length=32), nullable=False),
    sa.Column('schema_status', sa.String(length=32), nullable=False),
    sa.Column('enum_domain', sa.JSON(), nullable=True),
    sa.Column('reference_target_paths', sa.JSON(), nullable=True),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['common_field_id'], ['meta_common_field.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta_field_mapping_entity_scope'), 'meta_field_mapping', ['entity_scope'], unique=False)
    op.create_index(op.f('ix_meta_field_mapping_field_mapping_code'), 'meta_field_mapping', ['field_mapping_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meta_field_mapping_field_mapping_code'), table_name='meta_field_mapping')
    op.drop_index(op.f('ix_meta_field_mapping_entity_scope'), table_name='meta_field_mapping')
    op.drop_table('meta_field_mapping')
    op.drop_index(op.f('ix_product_product_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_meta_common_field_common_field_code'), table_name='meta_common_field')
    op.drop_table('meta_common_field')
    # ### end Alembic commands ###
